### PR TITLE
Create lang_es.txt

### PR DESCRIPTION
**Pull request by autopsia**
Spanish Translation

### CODE REVIEW

**Comment by wwwwwwzx** [comment]
Thank you

**Comment by RichardPaulAstley** [comment]
Hey, sorry for disturbing, but can I use that file for translating into French version ?
Thanks o/

**Comment by wwwwwwzx** [comment]
Yes do it the same way.
Other files can copy from https://github.com/kwsch/PKHeX/tree/master/PKHeX.Core/Resources/text
follow this https://github.com/wwwwwwzx/3DSRNGTool/commit/ebc0dd1340c5dbbf846cdedeca2a1ad90c540e56

**Comment by RichardPaulAstley** [comment]
Gonna try to do that in French for today if you need it o/

**Pull request merged**
